server:
  port: 8080

spring:
  application:
    name: windrunner

  datasource:
    url: jdbc:mysql://localhost:3306/windrunner?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver